# Generated by Django 5.0.8 on 2024-09-05 10:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_path', models.CharField(max_length=255)),
                ('remote_path', models.CharField(blank=True, max_length=255, null=True)),
                ('backup_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommGroup',
            fields=[
                ('CommGroup_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('CommGroup_code', models.CharField(max_length=10, unique=True)),
                ('soft_key', models.CharField(max_length=50)),
                ('activation_key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('interval', models.IntegerField()),
                ('equipment_type', models.CharField(max_length=255)),
                ('door_access_type', models.CharField(choices=[('none', 'None'), ('plc', 'PLC'), ('biometric', 'Biometric')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('sa_full_name', models.CharField(max_length=25)),
                ('sa_email', models.EmailField(max_length=254)),
                ('sa_username', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('sa_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('header_note', models.CharField(max_length=100)),
                ('footer_note', models.CharField(max_length=100)),
                ('report_datetime_stamp', models.BooleanField(default=False)),
                ('commGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.commgroup')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('login_name', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('password_duration', models.PositiveIntegerField(default=30)),
                ('role', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('accessible_departments', models.ManyToManyField(blank=True, related_name='accessible_departments', to='App1.department')),
                ('commGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.commgroup')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.department')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(default=django.utils.timezone.now)),
                ('log_time', models.TimeField(default=django.utils.timezone.now)),
                ('event_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.user')),
            ],
        ),
    ]
