# Generated by Django 5.0.8 on 2024-11-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturehumidityrecord',
            name='set_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperaturehumidityrecord',
            name='t_high_alarm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperaturehumidityrecord',
            name='t_high_alert',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperaturehumidityrecord',
            name='t_low_alarm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperaturehumidityrecord',
            name='t_low_alert',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
