# Generated by Django 5.0.8 on 2024-09-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.DeleteModel(
            name='Custom_User',
        ),
        migrations.DeleteModel(
            name='SuperAdmin',
        ),
    ]
