# Generated by Django 5.0.8 on 2025-01-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='email_sys_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='sms_sys_set',
            field=models.BooleanField(default=False),
        ),
    ]
