# Generated by Django 5.0.8 on 2025-01-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm_logs',
            name='ack_time',
            field=models.TimeField(null=True),
        ),
    ]
