# Generated by Django 5.0.8 on 2025-02-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='email_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='sms_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
