# Generated by Django 5.0.1 on 2024-08-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Custom_User',
        ),
    ]
