# Generated by Django 5.0.8 on 2025-02-17 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alter_department_email_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordhistory',
            name='superuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.superadmin'),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.user'),
        ),
    ]
