# Generated by Django 5.0.8 on 2024-11-23 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alter_temperaturehumidityrecord_set_temp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm_codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_log', models.CharField(max_length=100, null=True)),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='alarm_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('alarm_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.alarm_codes', to_field='code')),
            ],
        ),
    ]
