# Generated by Django 5.0.8 on 2025-02-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alter_appsettings_email_sys_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plcuser',
            name='code',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equip_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
