# Generated by Django 5.0.1 on 2024-08-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_rename_customuser_custom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
