# Generated by Django 5.0.8 on 2024-09-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_rename_user_users_delete_custom_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('sa_full_name', models.CharField(max_length=25)),
                ('sa_email', models.EmailField(max_length=254)),
                ('sa_username', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('sa_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
