# Generated by Django 5.0.8 on 2025-01-03 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alarm_logs_ack_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cooling',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='cooling_hum',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='high_alarm',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='high_alarm_hum',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='high_alert',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='equipment',
            name='high_alert_hum',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='equipment',
            name='low_alarm',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='low_alarm_hum',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='low_alert',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='equipment',
            name='low_alert_hum',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='equipment',
            name='set_value',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='set_value_hum',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='total_humidity_sensors',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='total_temp_sensors',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
