# Generated by Django 5.0.8 on 2024-11-25 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alarm_codes_alarm_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm_codes',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='alarm_logs',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.equipment'),
        ),
    ]
