# Generated by Django 5.0.8 on 2025-02-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_plcuser_code_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailalert',
            name='code_2001',
            field=models.BooleanField(default=False, help_text='Door Access By User 1'),
        ),
        migrations.AddField(
            model_name='emailalert',
            name='code_2002',
            field=models.BooleanField(default=False, help_text='Door Access By User 2'),
        ),
        migrations.AddField(
            model_name='emailalert',
            name='code_2003',
            field=models.BooleanField(default=False, help_text='Door Access By User 3'),
        ),
        migrations.AddField(
            model_name='emailalert',
            name='code_2004',
            field=models.BooleanField(default=False, help_text='Door Access By User 4'),
        ),
        migrations.AddField(
            model_name='emailalert',
            name='code_2005',
            field=models.BooleanField(default=False, help_text='Door Access By User 5'),
        ),
        migrations.AddField(
            model_name='emailalert',
            name='code_2006',
            field=models.BooleanField(default=False, help_text='Door Access By User 6'),
        ),
        migrations.AddField(
            model_name='emailalert',
            name='code_2007',
            field=models.BooleanField(default=False, help_text='Door Access By User 7'),
        ),
        migrations.AddField(
            model_name='emailalert',
            name='code_2008',
            field=models.BooleanField(default=False, help_text='Door Access By User 8'),
        ),
        migrations.AddField(
            model_name='emailalert',
            name='code_2009',
            field=models.BooleanField(default=False, help_text='Door Access By User 9'),
        ),
        migrations.AddField(
            model_name='emailalert',
            name='code_2010',
            field=models.BooleanField(default=False, help_text='Door Access By User 10'),
        ),
        migrations.AddField(
            model_name='emailalert',
            name='code_2011',
            field=models.BooleanField(default=False, help_text='Door Access By User 11'),
        ),
        migrations.AddField(
            model_name='emailalert',
            name='code_2012',
            field=models.BooleanField(default=False, help_text='Door Access By User 12'),
        ),
        migrations.AddField(
            model_name='emailalert',
            name='code_2013',
            field=models.BooleanField(default=False, help_text='Door Access By User 13'),
        ),
        migrations.AddField(
            model_name='emailalert',
            name='code_2014',
            field=models.BooleanField(default=False, help_text='Door Access By User 14'),
        ),
        migrations.AddField(
            model_name='emailalert',
            name='code_2015',
            field=models.BooleanField(default=False, help_text='Door Access By User 15'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='code_2001',
            field=models.BooleanField(default=False, help_text='Door Access By User 1'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='code_2002',
            field=models.BooleanField(default=False, help_text='Door Access By User 2'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='code_2003',
            field=models.BooleanField(default=False, help_text='Door Access By User 3'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='code_2004',
            field=models.BooleanField(default=False, help_text='Door Access By User 4'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='code_2005',
            field=models.BooleanField(default=False, help_text='Door Access By User 5'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='code_2006',
            field=models.BooleanField(default=False, help_text='Door Access By User 6'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='code_2007',
            field=models.BooleanField(default=False, help_text='Door Access By User 7'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='code_2008',
            field=models.BooleanField(default=False, help_text='Door Access By User 8'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='code_2009',
            field=models.BooleanField(default=False, help_text='Door Access By User 9'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='code_2010',
            field=models.BooleanField(default=False, help_text='Door Access By User 10'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='code_2011',
            field=models.BooleanField(default=False, help_text='Door Access By User 11'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='code_2012',
            field=models.BooleanField(default=False, help_text='Door Access By User 12'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='code_2013',
            field=models.BooleanField(default=False, help_text='Door Access By User 13'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='code_2014',
            field=models.BooleanField(default=False, help_text='Door Access By User 14'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='code_2015',
            field=models.BooleanField(default=False, help_text='Door Access By User 15'),
        ),
    ]
