# Generated by Django 5.0.8 on 2024-08-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alter_custom_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('sa_full_name', models.CharField(max_length=25)),
                ('sa_email', models.EmailField(max_length=254)),
                ('sa_username', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('sa_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='custom_user',
            old_name='department',
            new_name='Company_name',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='no_of_users',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
