# Generated by Django 5.0.8 on 2025-01-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_equipment_cooling_equipment_cooling_hum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='email_sys_set',
            field=models.CharField(default='Enable', max_length=100, null=True),
        ),
    ]
