# Generated by Django 5.0.8 on 2024-09-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_superadmin_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_name',
            field=models.CharField(max_length=255),
        ),
    ]
