# Generated by Django 5.0.8 on 2025-02-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_emailalert_code_2001_emailalert_code_2002_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
