# Generated by Django 5.0.8 on 2025-01-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alter_appsettings_email_sys_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='autologouttime',
            field=models.IntegerField(null=True),
        ),
    ]
