# Generated by Django 5.0.8 on 2024-12-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alarm_codes_remarks_alarm_logs_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm_logs',
            name='ack_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='alarm_logs',
            name='ack_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alarm_logs',
            name='acknowledge',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='alarm_logs',
            name='comments',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
