# Generated by Django 5.0.8 on 2024-09-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alter_user_login_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='report_datetime_stamp',
            field=models.BooleanField(default=False),
        ),
    ]
