# Generated by Django 5.0.8 on 2025-02-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_user_failed_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plcuser',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
