# Generated by Django 5.0.8 on 2024-12-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_alarm_logs_ack_date_alarm_logs_ack_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='autologouttime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='lockcount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='passwordchange',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='whatsapp_baud_rate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='whatsapp_comm_port',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='whatsapp_data_bits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='whatsapp_flow_control',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='whatsapp_parity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='whatsapp_stop_bits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
