# Generated by Django 5.0.8 on 2024-12-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_appsettings_autologouttime_appsettings_lockcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sms_alert',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='sms_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user10',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user10_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user1_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user2_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user3_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user4',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user4_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user5',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user5_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user6',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user6_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user7',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user7_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user8',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user8_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user9',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user9_num',
            field=models.IntegerField(null=True),
        ),
    ]
