# Generated by Django 5.0.8 on 2025-01-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_user_last_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_lock',
            field=models.BooleanField(default=False),
        ),
    ]
