# Generated by Django 5.0.8 on 2025-01-15 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_user_account_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('sys_mail', models.BooleanField(default=False)),
                ('to_email', models.EmailField(max_length=254)),
                ('email_sub', models.CharField(max_length=100, null=True)),
                ('email_body', models.TextField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Equipmentwrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('label', models.CharField(max_length=50, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=10)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Sms_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('sys_sms', models.BooleanField(default=False)),
                ('to_num', models.IntegerField(null=True)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('msg_body', models.TextField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.equipment')),
            ],
        ),
    ]
