# Generated by Django 5.0.8 on 2025-01-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_email_logs_equipmentwrite_sms_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_logs',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='email_logs',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='high_alert',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='high_alert_hum',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='low_alert',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='low_alert_hum',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
