# Generated by Django 5.0.8 on 2025-01-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_alter_email_logs_date_alter_email_logs_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentwrite',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equipmentwrite',
            name='login_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equipmentwrite',
            name='old_value',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
