# Generated by Django 5.0.8 on 2025-01-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_equipmentwrite_comment_equipmentwrite_login_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentwrite',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='equipmentwrite',
            name='time',
            field=models.TimeField(),
        ),
    ]
