# Generated by Django 5.0.8 on 2025-01-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_alter_equipmentwrite_date_alter_equipmentwrite_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='online',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
