# Generated by Django 5.0.8 on 2025-01-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0013_alter_equipment_high_alarm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='user10_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='user1_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='user2_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='user3_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='user4_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='user5_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='user6_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='user7_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='user8_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='user9_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sms_logs',
            name='to_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
