# Generated by Django 5.0.8 on 2025-01-23 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0015_user_access_db_a_act_p_user_access_db_a_act_v_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='email_alert',
            new_name='email_delay',
        ),
        migrations.RemoveField(
            model_name='department',
            name='sms_alert',
        ),
        migrations.AddField(
            model_name='department',
            name='email_sys',
            field=models.CharField(default='Enable', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='sms_sys',
            field=models.CharField(default='Enable', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='email_sys_set',
            field=models.CharField(default='Enable', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='sms_sys_set',
            field=models.CharField(default='Enable', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='EquipParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('t2color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('t3color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('t4color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('t5color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('t6color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('t7color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('t8color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('t9color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('t10color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('rh1color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('rh2color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('rh3color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('rh4color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('rh5color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('rh6color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('rh7color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('rh8color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('rh9color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('rh10color', models.CharField(blank=True, default='black', max_length=20, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.equipment')),
            ],
        ),
    ]
