# Generated by Django 5.0.8 on 2025-01-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0016_rename_email_alert_department_email_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sms_delay',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
