# Generated by Django 5.0.8 on 2025-01-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0017_department_sms_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='total_humidity_sensors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='total_temp_sensors',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
